// SPDX-License-Identifier: GPL-2.0-only
/*
 * Battery-voltage-aware CPU frequency cap for Qualcomm MSM8974.
 *
 * The Krait cores' shared rail is generated by a buck fed from VPH_PWR
 * (battery + charger).  Under sustained multi-core load at high frequency
 * the package draws more than a weak charger can supply; the battery covers
 * the deficit, its terminal voltage sags through the cell's internal
 * resistance, and once the buck's input headroom is gone the CPU rail
 * droops and the SoC silently resets (PS_HOLD - the PMIC's averaged UVLO
 * never trips).  Measured on a Fairphone 2: identical full load runs for
 * half an hour from a 4.25 V battery and dies within minutes below ~4.0 V.
 *
 * The stock firmware survives the whole discharge curve by demanding less
 * instead of supplying more: its BCL (battery current limit) mitigation
 * caps the CPU frequency when the battery runs low.  This driver is the
 * mainline-idiom equivalent: poll the battery voltage through an IIO
 * channel and hold a FREQ_QOS_MAX request on the CPU policy while VBAT is
 * below the cap threshold, releasing it (with hysteresis) once it recovers.
 *
 * Thresholds and the cap are device-tree properties with module-parameter
 * overrides so the policy can be tuned live while mapping a board's
 * load-vs-VBAT behaviour.
 */

#include <linux/cpufreq.h>
#include <linux/iio/consumer.h>
#include <linux/module.h>
#include <linux/of.h>
#include <linux/platform_device.h>
#include <linux/pm_qos.h>
#include <linux/workqueue.h>

static unsigned int vbat_low_uv;
module_param(vbat_low_uv, uint, 0644);
MODULE_PARM_DESC(vbat_low_uv, "cap the CPU frequency below this VBAT (uV)");

static unsigned int vbat_clear_uv;
module_param(vbat_clear_uv, uint, 0644);
MODULE_PARM_DESC(vbat_clear_uv, "release the cap above this VBAT (uV)");

static unsigned int cap_freq_khz;
module_param(cap_freq_khz, uint, 0644);
MODULE_PARM_DESC(cap_freq_khz, "frequency cap while VBAT is low (kHz)");

static unsigned int poll_ms;
module_param(poll_ms, uint, 0644);
MODULE_PARM_DESC(poll_ms, "battery voltage poll interval (ms)");

struct vbat_freqcap {
	struct device *dev;
	struct iio_channel *vbat;
	struct freq_qos_request qos;
	struct cpufreq_policy *policy;
	struct delayed_work work;
	bool capped;
};

static void vbat_freqcap_work(struct work_struct *work)
{
	struct vbat_freqcap *vfc =
		container_of(work, struct vbat_freqcap, work.work);
	int uv, ret;

	ret = iio_read_channel_processed(vfc->vbat, &uv);
	if (ret < 0) {
		dev_warn_ratelimited(vfc->dev, "vbat read failed: %d\n", ret);
		goto resched;
	}

	if (!vfc->capped && uv < vbat_low_uv) {
		ret = freq_qos_update_request(&vfc->qos, cap_freq_khz);
		if (ret >= 0) {
			vfc->capped = true;
			dev_info(vfc->dev,
				 "VBAT %d uV low: capping the CPU at %u kHz\n",
				 uv, cap_freq_khz);
		}
	} else if (vfc->capped && uv > vbat_clear_uv) {
		ret = freq_qos_update_request(&vfc->qos,
					      FREQ_QOS_MAX_DEFAULT_VALUE);
		if (ret >= 0) {
			vfc->capped = false;
			dev_info(vfc->dev,
				 "VBAT %d uV recovered: cap released\n", uv);
		}
	}

resched:
	schedule_delayed_work(&vfc->work, msecs_to_jiffies(poll_ms));
}

static int vbat_freqcap_probe(struct platform_device *pdev)
{
	struct device *dev = &pdev->dev;
	struct vbat_freqcap *vfc;
	u32 val;
	int ret;

	vfc = devm_kzalloc(dev, sizeof(*vfc), GFP_KERNEL);
	if (!vfc)
		return -ENOMEM;
	vfc->dev = dev;

	/*
	 * The CPU policy and the ADC both come up late; defer until they
	 * exist rather than running without either.
	 */
	vfc->vbat = devm_iio_channel_get(dev, "vbat");
	if (IS_ERR(vfc->vbat))
		return dev_err_probe(dev, PTR_ERR(vfc->vbat),
				     "no vbat channel\n");

	vfc->policy = cpufreq_cpu_get(0);
	if (!vfc->policy)
		return -EPROBE_DEFER;

	/* DT defaults; module params (when set) win so tuning needs no DT edit. */
	if (!vbat_low_uv)
		vbat_low_uv = !of_property_read_u32(dev->of_node,
				"qcom,vbat-low-microvolt", &val) ? val : 3800000;
	if (!vbat_clear_uv)
		vbat_clear_uv = !of_property_read_u32(dev->of_node,
				"qcom,vbat-clear-microvolt", &val) ? val : 3950000;
	if (!cap_freq_khz)
		cap_freq_khz = !of_property_read_u32(dev->of_node,
				"qcom,cap-freq-khz", &val) ? val : 960000;
	if (!poll_ms)
		poll_ms = !of_property_read_u32(dev->of_node,
				"qcom,poll-ms", &val) ? val : 1000;

	ret = freq_qos_add_request(&vfc->policy->constraints, &vfc->qos,
				   FREQ_QOS_MAX, FREQ_QOS_MAX_DEFAULT_VALUE);
	if (ret < 0) {
		cpufreq_cpu_put(vfc->policy);
		return dev_err_probe(dev, ret, "freq qos request failed\n");
	}

	INIT_DELAYED_WORK(&vfc->work, vbat_freqcap_work);
	platform_set_drvdata(pdev, vfc);
	schedule_delayed_work(&vfc->work, msecs_to_jiffies(poll_ms));

	dev_info(dev, "active: cap %u kHz below %u uV, clear above %u uV, poll %u ms\n",
		 cap_freq_khz, vbat_low_uv, vbat_clear_uv, poll_ms);
	return 0;
}

static void vbat_freqcap_remove(struct platform_device *pdev)
{
	struct vbat_freqcap *vfc = platform_get_drvdata(pdev);

	cancel_delayed_work_sync(&vfc->work);
	freq_qos_remove_request(&vfc->qos);
	cpufreq_cpu_put(vfc->policy);
}

static const struct of_device_id vbat_freqcap_of_match[] = {
	{ .compatible = "qcom,vbat-freqcap" },
	{ }
};
MODULE_DEVICE_TABLE(of, vbat_freqcap_of_match);

static struct platform_driver vbat_freqcap_driver = {
	.probe = vbat_freqcap_probe,
	.remove = vbat_freqcap_remove,
	.driver = {
		.name = "qcom-vbat-freqcap",
		.of_match_table = vbat_freqcap_of_match,
	},
};
module_platform_driver(vbat_freqcap_driver);

MODULE_DESCRIPTION("Battery-voltage-aware CPU frequency cap");
MODULE_LICENSE("GPL");
